import type {Metadata} from 'next'
import localFont from 'next/font/local'
import './globals.css'
import {ThemeProvider} from 'next-themes'
import {Toaster} from '@/components/ui/toaster'
import ModbusContextProvider from '@/lib/modbus/ModbusContext'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ModbusContextProvider>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
            <div className=" mx-auto">{children}</div>
            <Toaster />
          </ThemeProvider>
        </ModbusContextProvider>
      </body>
    </html>
  )
}
